### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by ainarill** [Teichlab/cell2tcr#4]
Hi! nice tool! I am struggling to run the pipeline. Could you explain a little bit more what is the format that you need in order to run your code? How can we bridge exactly the data format from scirpy to your input object?

**Comment by lisadratva** [comment]
Hi @ainarill ,

Thanks for your comment! Your data has to be a pandas dataframe. If your columns don't have the typical scirpy names, you can rename them as shown in the tutorial and written out again here:

```
# format to match Scirpy
for i, j in zip(
    ['individual', 'IR_VDJ_1_junction_aa','IR_VDJ_1_v_call','IR_VDJ_1_j_call','IR_VJ_1_junction_aa','IR_VJ_1_v_call','IR_VJ_1_j_call'], # Scirpy format - leave unchanged
    ['your_patient_id', 'your_tcr_b_aa','your_tcr_b_v','your_tcr_b_j','your_tcr_a_aa','your_tcr_a_v','your_tcr_a_j']): # your format - modify to match your column names
    df.loc[:,i] = df.loc[:,j].copy()
    
```

Simply replace 'your_XXX' with your column names. Hope this helps!

**Comment by lisadratva** [comment]
Hi @ainarill, there is a new function `cell2tcr.assign_column_names` available on the `db_extension` branch of Cell2TCR that allows you to assign column names and includes more explanation on the inputs. Hope this helps with running the pipeline. Closing this issue now, feel free to reopen if your problem persists.
